# Generated by Django 6.0.4 on 2026-04-26 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('color', models.CharField(default='#333333', max_length=50, verbose_name='Цвет темы')),
                ('flag', models.CharField(blank=True, max_length=200, verbose_name='Путь к флагу')),
                ('region_name', models.CharField(default='Регионы', max_length=50, verbose_name='Название регионов')),
                ('politics', models.TextField(blank=True, verbose_name='Политика')),
                ('military', models.TextField(blank=True, verbose_name='Военная политика')),
                ('income', models.TextField(blank=True, verbose_name='Доход')),
                ('ruling_house', models.CharField(blank=True, max_length=100, verbose_name='Правящий род')),
                ('current_ruler', models.CharField(blank=True, max_length=100, verbose_name='Текущий правитель')),
                ('heir', models.CharField(blank=True, max_length=100, verbose_name='Наследник')),
                ('fact', models.TextField(blank=True, verbose_name='Интересный факт')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('flag', models.CharField(blank=True, max_length=200, verbose_name='Путь к флагу')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='main.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
