# Generated by Django 6.0.4 on 2026-04-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные (язык, религия, тингства, уезды)'),
        ),
    ]
