# Generated by Django 6.0.4 on 2026-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
