# Generated by Django 6.0.4 on 2026-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_region_options_countryaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Короткое название')),
                ('flag', models.CharField(max_length=200, verbose_name='Путь к флагу')),
                ('goal', models.TextField(verbose_name='Цель')),
                ('alliance_type', models.CharField(max_length=100, verbose_name='Тип объединения')),
                ('color', models.CharField(default='#333333', max_length=50, verbose_name='Цвет темы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('members', models.ManyToManyField(blank=True, to='main.country', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Союз',
                'verbose_name_plural': 'Союзы',
            },
        ),
    ]
