# Generated by Django 6.0.4 on 2026-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alliance',
            name='color',
        ),
        migrations.RemoveField(
            model_name='alliance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alliance',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='alliance',
            name='alliance_type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='flag',
            field=models.CharField(max_length=200, verbose_name='Ссылка на флаг'),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Адрес страницы'),
        ),
    ]
